/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TableSelectorPanel.java
 *
 * Created on 18.8.2010, 10:37:39
 */

package org.netbeans.modules.php.nette.generators.form;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import org.netbeans.api.db.explorer.DatabaseConnection;
import org.openide.util.Exceptions;

/**
 *
 * @author Foowie
 */
public class TableSelectorPanel extends javax.swing.JPanel {

    /** Creates new form TableSelectorPanel */
    public TableSelectorPanel() {
        initComponents();
		init();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        connectionComboBox = new javax.swing.JComboBox();
        tableComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        componentNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        connectionComboBox.setModel(new DatabaseConnectionComboBoxModel());

        tableComboBox.setEnabled(false);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(TableSelectorPanel.class, "TableSelectorPanel.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(TableSelectorPanel.class, "TableSelectorPanel.jLabel2.text")); // NOI18N

        componentNameTextField.setText(org.openide.util.NbBundle.getMessage(TableSelectorPanel.class, "TableSelectorPanel.componentNameTextField.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(TableSelectorPanel.class, "TableSelectorPanel.jLabel3.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(connectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(componentNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(connectionComboBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(tableComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(componentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void init() {
		this.connectionComboBox.addActionListener(new ActionListener() {
			@Override
			public void actionPerformed(ActionEvent e) {
				onDatabaseConnectionSelected();
			}
		});
		this.connectionComboBox.setRenderer(new DatabaseConnectionComboBoxRenderer());
	}

	public void onDatabaseConnectionSelected() {
		DatabaseConnection databaseConnection = (DatabaseConnection)connectionComboBox.getSelectedItem();
		DefaultComboBoxModel model = (DefaultComboBoxModel)this.tableComboBox.getModel();
		model.removeAllElements();
		if(databaseConnection == null) {
			// disable table select
			tableComboBox.setEnabled(false);
		} else {
			//load tables
			Connection conn = databaseConnection.getJDBCConnection();
			try {
				ResultSet rs = conn.getMetaData().getTables(conn.getCatalog(), databaseConnection.getSchema(), null, new String[] {"TABLE", "VIEW"});
				while(rs.next()) {
					String tableSchema = rs.getString("TABLE_SCHEM");
					String tableName = rs.getString("TABLE_NAME");
					model.addElement(new TableInfo(tableName, tableSchema, databaseConnection));
				}
				tableComboBox.setEnabled(true);
			} catch (SQLException ex) {
				this.connectionComboBox.setSelectedItem(null);
				Exceptions.printStackTrace(ex);
			}
		}
	}

	public TableInfo getSelectedTable() {
		return (TableInfo)this.tableComboBox.getSelectedItem();
	}

	public String getComponentName() {
		return componentNameTextField.getText();
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField componentNameTextField;
    private javax.swing.JComboBox connectionComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox tableComboBox;
    // End of variables declaration//GEN-END:variables


}
